package br.gasmartins.payments.infra.persistence.entity;

import br.gasmartins.payments.infra.persistence.converter.LocalDatetimeDynamoDBTypeConverter;
import br.gasmartins.payments.infra.persistence.enums.PaymentStatusData;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Builder(setterPrefix = "with")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@DynamoDBTable(tableName = "payments")
public class PaymentEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName = "order_id")
    private UUID orderId;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private PaymentStatusData status;

    @DynamoDBAttribute(attributeName = "processed_at")
    @DynamoDBTypeConverted(converter = LocalDatetimeDynamoDBTypeConverter.class)
    private LocalDateTime processedAt;

    @DynamoDBAttribute(attributeName = "total_amount")
    private BigDecimal totalAmount;

    @DynamoDBAttribute(attributeName = "total_discount")
    private BigDecimal totalDiscount;

}
