version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass redis
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 8001:8001
