spring:
  application:
    name: payment-service
  main:
    allow-bean-definition-overriding: true
  sleuth:
    opentracing:
      enabled: true
    trace-id128: true
  redis:
    client-type: JEDIS
    client-name: ${spring.application.name}
    password: 'redis'
    ssl: false
    jedis:
      pool:
        enabled: true

topic:
  order-topic: order-topic
  payment-topic: payment-topic

aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: sa-east-1
    credentials:
      access-key: 'default_access_key'
      secret-key: 'default_secret_key'