package br.gasmartins.orders.infra.persistence.entity;

import br.gasmartins.orders.infra.persistence.converter.LocalDatetimeDynamoDBTypeConverter;
import br.gasmartins.orders.infra.persistence.enums.StatusData;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;


@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@Builder(setterPrefix = "with")
@DynamoDBTable(tableName = "orders")
public class OrderEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName = "status")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private StatusData status;

    @DynamoDBAttribute(attributeName = "created_at")
    @DynamoDBTypeConverted(converter = LocalDatetimeDynamoDBTypeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute(attributeName = "finished_at")
    @DynamoDBTypeConverted(converter = LocalDatetimeDynamoDBTypeConverter.class)
    private LocalDateTime finishedAt;

    @DynamoDBAttribute(attributeName = "total_amount")
    private BigDecimal totalAmount;

    @DynamoDBAttribute(attributeName = "total_discount")
    private BigDecimal totalDiscount;

    @DynamoDBAttribute(attributeName = "items")
    @Singular("addItem")
    private List<OrderItemEntity> items;


}
